
// src/lib/mock-asset-data.ts
import { AssetManagementFormData } from "./schemas";
import { DEPARTMENTS } from "./constants";

export const mockAssetData: AssetManagementFormData[] = [
    {
        id: "ASSET-001",
        assetNumber: "KONE-RD-LAP-001",
        materialCode: "KM-LAP-DELL-5420",
        assetDescription: "Dell Latitude 5420 Laptop",
        assetClassification: "IT Equipment",
        assetGrouping: "Laptops",
        lifecycleYears: 5,
        capitalizationDate: new Date("2022-01-15"),
        purchaseValue: 120000,
        ledgerQty: 1,
        brandName: "Dell",
        modelNo: "Latitude 5420",
        productSerialNo: "SN-LAP-12345",
        onGoingProject: "Project Phoenix",
        weeklyUsageFrequency: 5,
        personResponsible: "Ram Kumar",
        currentUser: "Ram Kumar",
        teamOrTribe: "R&D Core Team",
        department: "R&D",
        assetCoordinator: "Admin Ram",
        location: "KOSMO Building",
        floor: "3rd Floor",
        laboratory: "R&D Electronics Lab",
        verificationStatus: "Verified",
        verifiedOn: new Date("2024-07-01"),
        usableCondition: "Yes",
        workingConditionStatus: "Working",
        comments: "In good working condition.",
        currentStatus: "In Use",
        statusChangedOn: new Date("2022-01-20"),
    },
    {
        id: "ASSET-002",
        assetNumber: "KONE-RD-OSC-001",
        materialCode: "KM-OSC-TEK-2024",
        assetDescription: "Tektronix Oscilloscope",
        assetClassification: "Test Equipment",
        assetGrouping: "Measurement Devices",
        lifecycleYears: 10,
        capitalizationDate: new Date("2020-05-20"),
        purchaseValue: 450000,
        ledgerQty: 1,
        brandName: "Tektronix",
        modelNo: "TBS2000B",
        productSerialNo: "SN-OSC-67890",
        department: "R&D",
        location: "KOSMO Building",
        floor: "3rd Floor",
        laboratory: "R&D Electronics Lab",
        verificationStatus: "Verified",
        verifiedOn: new Date("2024-07-01"),
        usableCondition: "Yes",
        workingConditionStatus: "Working",
        currentStatus: "In Use",
    },
    {
        id: "ASSET-003",
        assetNumber: "KONE-MAINT-TOOL-001",
        materialCode: "KM-TOOL-FLU-87V",
        assetDescription: "Fluke 87V Multimeter",
        assetClassification: "Tools & Tackles",
        assetGrouping: "Handheld Tools",
        lifecycleYears: 8,
        capitalizationDate: new Date("2021-11-10"),
        purchaseValue: 35000,
        ledgerQty: 1,
        brandName: "Fluke",
        modelNo: "87V",
        productSerialNo: "SN-MM-11223",
        personResponsible: "Praveen S.",
        currentUser: "Maintenance Team Pool",
        department: "Maintenance",
        location: "Test Tower",
        floor: "Ground Floor",
        laboratory: "Maintenance Workshop",
        verificationStatus: "Pending",
        usableCondition: "Yes",
        workingConditionStatus: "Working",
        currentStatus: "In Store",
    },
    {
        id: "ASSET-004",
        assetNumber: "KONE-RD-3DP-001",
        materialCode: "KM-3DP-ULT-S5",
        assetDescription: "Ultimaker S5 3D Printer",
        assetClassification: "Prototyping Equipment",
        assetGrouping: "3D Printers",
        lifecycleYears: 7,
        capitalizationDate: new Date("2019-08-01"),
        purchaseValue: 800000,
        ledgerQty: 1,
        brandName: "Ultimaker",
        modelNo: "S5",
        productSerialNo: "SN-3DP-44556",
        personResponsible: "Chandrasekar R.",
        currentUser: "Chandrasekar R.",
        department: "R&D",
        location: "KOSMO Building",
        floor: "3rd Floor",
        laboratory: "R&D Mechanical Lab",
        verificationStatus: "Discrepancy",
        verifiedOn: new Date("2024-06-28"),
        usableCondition: "Yes",
        workingConditionStatus: "Under Maintenance",
        comments: "Minor feeding issue reported. Needs calibration.",
        currentStatus: "Under Maintenance",
        statusChangedOn: new Date("2024-07-15"),
    },
];
