
// src/lib/mock-asset-data.ts
import { AssetManagementFormData } from "./schemas";

export const mockAssetData: AssetManagementFormData[] = [
    {
        id: "ASSET-001",
        assetNumber: "KONE-RD-LAP-001",
        kmNumber: "KM-LAP-DELL-5420",
        assetDescription: "Dell Latitude 5420 Laptop",
        assetClassification: "IT Equipment",
        assetGrouping: "Laptops",
        lifecycleYears: 5,
        capitalizationDate: new Date("2022-01-15"),
        eolDate: new Date("2027-01-14"),
        purchaseValue: 120000,
        ledgerQty: 1,
        brandName: "Dell",
        modelNo: "Latitude 5420",
        productSerialNo: "SN-LAP-12345",
        onGoingProject: "Project Phoenix",
        weeklyUsageFrequency: 5,
        personResponsible: "Ram Kumar",
        currentUser: "Ram Kumar",
        teamOrTribe: "R&D Core Team",
        department: "R&D",
        assetCoordinator: "Admin Ram",
        location: "ITEC",
        floor: "3rd Floor",
        laboratory: "R&D Electronics Lab",
        verificationStatus: "Verified",
        verifiedOn: new Date("2024-07-01"),
        usableCondition: "Yes",
        workingConditionStatus: "Working",
        comments: "In good working condition.",
        currentStatus: "In Use",
        statusChangedOn: new Date("2022-01-20"),
    },
    {
        id: "ASSET-002",
        assetNumber: "KONE-RD-OSC-001",
        kmNumber: "KM-OSC-TEK-2024",
        assetDescription: "Tektronix Oscilloscope",
        assetClassification: "Test Equipment",
        assetGrouping: "Measurement Devices",
        lifecycleYears: 10,
        capitalizationDate: new Date("2020-05-20"),
        eolDate: new Date("2030-05-19"),
        purchaseValue: 450000,
        ledgerQty: 1,
        brandName: "Tektronix",
        modelNo: "TBS2000B",
        productSerialNo: "SN-OSC-67890",
        department: "R&D",
        location: "ITEC",
        floor: "3rd Floor",
        laboratory: "R&D Electronics Lab",
        verificationStatus: "Verified",
        verifiedOn: new Date("2024-07-01"),
        usableCondition: "Yes",
        workingConditionStatus: "Working",
        currentStatus: "Active",
    },
    {
        id: "ASSET-003",
        assetNumber: "KONE-MAINT-TOOL-001",
        kmNumber: "KM-TOOL-FLU-87V",
        assetDescription: "Fluke 87V Multimeter",
        assetClassification: "Tools & Tackles",
        assetGrouping: "Handheld Tools",
        lifecycleYears: 8,
        capitalizationDate: new Date("2021-11-10"),
        eolDate: new Date("2029-11-09"),
        purchaseValue: 35000,
        ledgerQty: 1,
        brandName: "Fluke",
        modelNo: "87V",
        productSerialNo: "SN-MM-11223",
        personResponsible: "Praveen S.",
        currentUser: "Maintenance Team Pool",
        department: "Maintenance",
        location: "TT",
        floor: "Ground Floor",
        laboratory: "Maintenance Workshop",
        verificationStatus: "Pending",
        usableCondition: "Yes",
        workingConditionStatus: "Working",
        currentStatus: "In Store",
    },
    {
        id: "ASSET-004",
        assetNumber: "KONE-RD-3DP-001",
        kmNumber: "KM-3DP-ULT-S5",
        assetDescription: "Ultimaker S5 3D Printer",
        assetClassification: "Prototyping Equipment",
        assetGrouping: "3D Printers",
        lifecycleYears: 7,
        capitalizationDate: new Date("2019-08-01"),
        eolDate: new Date("2026-07-31"),
        purchaseValue: 800000,
        ledgerQty: 1,
        brandName: "Ultimaker",
        modelNo: "S5",
        productSerialNo: "SN-3DP-44556",
        personResponsible: "Chandrasekar R.",
        currentUser: "Chandrasekar R.",
        department: "R&D",
        location: "ITEC",
        floor: "3rd Floor",
        laboratory: "R&D Mechanical Lab",
        verificationStatus: "Discrepancy",
        verifiedOn: new Date("2024-06-28"),
        usableCondition: "Yes",
        workingConditionStatus: "Under Maintenance",
        comments: "Minor feeding issue reported. Needs calibration.",
        currentStatus: "Calibration",
        statusChangedOn: new Date("2024-07-15"),
    },
    {
        id: "ASSET-005",
        assetNumber: "KONE-SITE-LASER-01",
        kmNumber: "KM-LASER-LEICA-Disto",
        assetDescription: "Leica Disto Laser Measurer",
        assetClassification: "Test Equipment",
        assetGrouping: "Site Tools",
        lifecycleYears: 6,
        capitalizationDate: new Date("2023-02-01"),
        eolDate: new Date("2029-01-31"),
        purchaseValue: 45000,
        ledgerQty: 1,
        brandName: "Leica",
        modelNo: "Disto X4",
        productSerialNo: "SN-LAS-98765",
        personResponsible: "Site Manager",
        currentUser: "Field Team A",
        department: "SR Engineering",
        location: "Site",
        floor: "N/A",
        laboratory: "N/A",
        verificationStatus: "Pending",
        usableCondition: "Yes",
        workingConditionStatus: "Working",
        currentStatus: "In Use",
    },
    {
        id: "ASSET-006",
        assetNumber: "KONE-FIN-LAP-002",
        kmNumber: "KM-LAP-LENOVO-T14",
        assetDescription: "Lenovo ThinkPad T14",
        assetClassification: "IT Equipment",
        assetGrouping: "Laptops",
        lifecycleYears: 5,
        capitalizationDate: new Date("2023-03-20"),
        eolDate: new Date("2028-03-19"),
        purchaseValue: 135000,
        ledgerQty: 1,
        brandName: "Lenovo",
        modelNo: "ThinkPad T14",
        productSerialNo: "SN-LAP-LEN-001",
        personResponsible: "Prem Kumar",
        currentUser: "Prem Kumar",
        department: "Finance",
        location: "ITEC",
        floor: "4th Floor",
        verificationStatus: "Verified",
        verifiedOn: new Date("2024-07-10"),
        usableCondition: "Yes",
        workingConditionStatus: "Working",
        currentStatus: "In Use",
    },
    {
        id: "ASSET-007",
        assetNumber: "KONE-PROD-SERVER-01",
        kmNumber: "KM-SRV-HP-DL380",
        assetDescription: "HPE ProLiant DL380 Server",
        assetClassification: "IT Equipment",
        assetGrouping: "Servers",
        lifecycleYears: 8,
        capitalizationDate: new Date("2021-09-01"),
        eolDate: new Date("2029-08-31"),
        purchaseValue: 750000,
        ledgerQty: 1,
        brandName: "HPE",
        modelNo: "ProLiant DL380 Gen10",
        productSerialNo: "SN-SRV-HP-002",
        department: "IT",
        location: "ITEC",
        floor: "2nd Floor",
        laboratory: "Data Center",
        verificationStatus: "Pending",
        currentStatus: "Active",
    },
    {
        id: "ASSET-008",
        assetNumber: "KONE-QA-MICROSCOPE-01",
        kmNumber: "KM-MIC-OLY-BX53",
        assetDescription: "Olympus BX53 Microscope",
        assetClassification: "Lab Equipment",
        assetGrouping: "Quality Inspection",
        lifecycleYears: 12,
        capitalizationDate: new Date("2018-04-12"),
        eolDate: new Date("2030-04-11"),
        purchaseValue: 1200000,
        ledgerQty: 1,
        brandName: "Olympus",
        modelNo: "BX53",
        productSerialNo: "SN-MIC-OLY-001",
        department: "Quality Assurance",
        location: "Labs",
        floor: "1st Floor",
        laboratory: "QA Lab",
        currentStatus: "Calibration",
    },
    {
        id: "ASSET-009",
        assetNumber: "KONE-FAC-CHAIR-050",
        kmNumber: "KM-CHR-HERMAN-AERON",
        assetDescription: "Herman Miller Aeron Chair",
        assetClassification: "Furniture & Fixtures",
        assetGrouping: "Office Furniture",
        lifecycleYears: 15,
        capitalizationDate: new Date("2022-02-10"),
        eolDate: new Date("2037-02-09"),
        purchaseValue: 90000,
        ledgerQty: 1,
        brandName: "Herman Miller",
        modelNo: "Aeron",
        productSerialNo: "", // Missing Serial Number
        department: "Facility Management",
        location: "ITEC",
        floor: "3rd Floor",
        currentStatus: "In Use",
    },
    {
        id: "ASSET-010",
        assetNumber: "KONE-VEH-CAR-01",
        kmNumber: "KM-CAR-TOYOTA-INNOVA",
        assetDescription: "Toyota Innova Crysta",
        assetClassification: "Vehicles",
        assetGrouping: "Company Cars",
        lifecycleYears: 10,
        capitalizationDate: new Date("2023-01-05"),
        eolDate: new Date("2033-01-04"),
        purchaseValue: 2500000,
        ledgerQty: 1,
        brandName: "Toyota",
        modelNo: "Innova Crysta",
        productSerialNo: "CHASSIS-12345",
        department: "Logistics",
        location: "TT",
        currentStatus: "Active",
    },
    {
        id: "ASSET-011",
        assetNumber: "KONE-LOG-FORKLIFT-01",
        kmNumber: "KM-FL-GODREJ-GX",
        assetDescription: "Godrej GX Series Forklift",
        assetClassification: "Machinery",
        assetGrouping: "Warehouse Equipment",
        lifecycleYears: 15,
        capitalizationDate: new Date("2017-06-20"),
        eolDate: new Date("2032-06-19"),
        purchaseValue: 1800000,
        ledgerQty: 1,
        brandName: "Godrej",
        modelNo: "GX Series",
        productSerialNo: "SN-FL-GOD-001",
        department: "Logistics",
        location: "TT",
        currentStatus: "Active",
    },
    {
        id: "ASSET-012",
        assetNumber: "KONE-RD-POWER-01",
        kmNumber: "KM-PS-KEYSIGHT-E36",
        assetDescription: "Keysight E36313A Power Supply",
        assetClassification: "Test Equipment",
        assetGrouping: "Measurement Devices",
        lifecycleYears: 10,
        capitalizationDate: new Date("2022-08-11"),
        eolDate: new Date("2032-08-10"),
        purchaseValue: 250000,
        ledgerQty: 1,
        brandName: "Keysight",
        modelNo: "E36313A",
        productSerialNo: "SN-PS-KEY-005",
        department: "R&D",
        location: "ITEC",
        laboratory: "R&D Electronics Lab",
        currentStatus: "In Store",
    },
    {
        id: "ASSET-013",
        assetNumber: "KONE-IT-PROJECTOR-05",
        kmNumber: "KM-PROJ-EPSON-EB",
        assetDescription: "Epson EB-X06 Projector",
        assetClassification: "IT Equipment",
        assetGrouping: "AV Equipment",
        lifecycleYears: 7,
        capitalizationDate: new Date("2023-05-15"),
        eolDate: new Date("2030-05-14"),
        purchaseValue: 65000,
        ledgerQty: 1,
        brandName: "Epson",
        modelNo: "EB-X06",
        productSerialNo: "SN-PROJ-EPS-012",
        department: "IT",
        location: "ITEC",
        floor: "4th Floor",
        laboratory: "Conference Room 4B",
        currentStatus: "Active",
    },
    {
        id: "ASSET-014",
        assetNumber: "KONE-PROD-CNC-01",
        kmNumber: "KM-CNC-HAAS-VF2",
        assetDescription: "Haas VF-2 CNC Machine",
        assetClassification: "Machinery",
        assetGrouping: "Production Machinery",
        lifecycleYears: 20,
        capitalizationDate: new Date("2015-03-10"),
        eolDate: new Date("2035-03-09"),
        purchaseValue: 8500000,
        ledgerQty: 1,
        brandName: "Haas",
        modelNo: "VF-2",
        productSerialNo: "SN-CNC-HAAS-001",
        department: "Production",
        location: "TT",
        currentStatus: "Under Maintenance",
    },
    {
        id: "ASSET-015",
        assetNumber: "KONE-HR-LAP-01",
        kmNumber: "KM-LAP-APPLE-MBA",
        assetDescription: "Apple MacBook Air",
        assetClassification: "IT Equipment",
        assetGrouping: "Laptops",
        lifecycleYears: 5,
        capitalizationDate: new Date("2024-01-20"),
        eolDate: new Date("2029-01-19"),
        purchaseValue: 110000,
        ledgerQty: 1,
        brandName: "Apple",
        modelNo: "MacBook Air M2",
        productSerialNo: "SN-LAP-APP-003",
        department: "HR",
        location: "ITEC",
        currentStatus: "In Use",
    },
    {
        id: "ASSET-016",
        assetNumber: "KONE-RD-SPECAN-01",
        kmNumber: "KM-SA-RNS-FPL1000",
        assetDescription: "Rohde & Schwarz FPL1000 Spectrum Analyzer",
        assetClassification: "Test Equipment",
        assetGrouping: "RF Equipment",
        lifecycleYears: 12,
        capitalizationDate: new Date("2022-11-30"),
        eolDate: new Date("2034-11-29"),
        purchaseValue: 1500000,
        ledgerQty: 1,
        brandName: "Rohde & Schwarz",
        modelNo: "FPL1000",
        productSerialNo: "SN-SA-RNS-001",
        department: "R&D",
        location: "ITEC",
        laboratory: "RF Lab",
        currentStatus: "Active",
    },
    {
        id: "ASSET-017",
        assetNumber: "KONE-SAFETY-HARNESS-25",
        kmNumber: "KM-HARN-KARAM-PN56",
        assetDescription: "Karam PN56 Safety Harness",
        assetClassification: "Tools & Tackles",
        assetGrouping: "Safety Equipment",
        lifecycleYears: 3,
        capitalizationDate: new Date("2023-09-01"),
        eolDate: new Date("2026-08-31"),
        purchaseValue: 8000,
        ledgerQty: 1,
        brandName: "Karam",
        modelNo: "PN56",
        productSerialNo: "SN-HARN-KARAM-105",
        department: "Safety & Environment",
        location: "TT",
        currentStatus: "In Store",
    },
    {
        id: "ASSET-018",
        assetNumber: "KONE-OLD-DESKTOP-01",
        kmNumber: "KM-DESK-OLD-01",
        assetDescription: "Old Dell Optiplex Desktop",
        assetClassification: "IT Equipment",
        assetGrouping: "Desktops",
        lifecycleYears: 8,
        capitalizationDate: new Date("2015-01-01"),
        eolDate: new Date("2023-01-01"),
        purchaseValue: 60000,
        ledgerQty: 1,
        brandName: "Dell",
        modelNo: "Optiplex 7010",
        productSerialNo: "SN-DESK-OLD-01",
        department: "IT",
        location: "Scrap Yard",
        currentStatus: "Scrapped",
    },
    {
        id: "ASSET-019",
        assetNumber: "KONE-RD-ROBOTARM-01",
        kmNumber: "KM-ROBO-UR-UR5E",
        assetDescription: "Universal Robots UR5e",
        assetClassification: "Machinery",
        assetGrouping: "Robotics",
        lifecycleYears: 10,
        capitalizationDate: new Date("2023-07-15"),
        eolDate: new Date("2033-07-14"),
        purchaseValue: 3500000,
        ledgerQty: 1,
        brandName: "Universal Robots",
        modelNo: "UR5e",
        productSerialNo: "SN-ROBO-UR-001",
        department: "R&D",
        location: "ITEC",
        laboratory: "Automation Lab",
        currentStatus: "Reserved",
    },
    {
        id: "ASSET-020",
        assetNumber: "KONE-FIN-PRINTER-01",
        kmNumber: "KM-PRN-HP-LJ400",
        assetDescription: "HP LaserJet Pro 400",
        assetClassification: "IT Equipment",
        assetGrouping: "Printers",
        lifecycleYears: 6,
        capitalizationDate: new Date("2019-12-01"),
        eolDate: new Date("2025-11-30"),
        purchaseValue: 25000,
        ledgerQty: 1,
        brandName: "HP",
        modelNo: "LaserJet Pro 400",
        productSerialNo: "SN-PRN-HP-020",
        department: "Finance",
        location: "ITEC",
        floor: "4th Floor",
        currentStatus: "Not Working",
        comments: "Paper jam issue, needs service.",
    },
    {
        id: "ASSET-021",
        assetNumber: "KONE-TEST-001",
        kmNumber: "KM-TEST-001",
        assetDescription: "New Test Asset",
        assetClassification: "IT Equipment",
        assetGrouping: "General IT Pool",
        lifecycleYears: 5,
        capitalizationDate: new Date("2024-08-01"),
        eolDate: new Date("2029-07-31"),
        purchaseValue: 5000,
        ledgerQty: 1,
        brandName: "TestBrand",
        modelNo: "TestModel-123",
        productSerialNo: "SN-TEST-001",
        onGoingProject: "Internal Testing",
        weeklyUsageFrequency: 3,
        personResponsible: "Ram Kumar",
        currentUser: "Praveen S.",
        teamOrTribe: "R&D Core Team",
        department: "IT",
        assetCoordinator: "Ram Kumar V",
        location: "ITEC",
        floor: "1st",
        laboratory: "Test Lab",
        verificationStatus: "Pending",
        verifiedOn: undefined,
        usableCondition: "Yes",
        workingConditionStatus: "Working",
        comments: "This is a new asset created for testing purposes.",
        currentStatus: "In Store",
        statusChangedOn: new Date("2024-08-01"),
    },
];

    